# Tutorial 1: Accessing Datasets

This tutorial demonstrates how to retrieve data using the *datasets* module.

## Datasets Classes
The datasets module contains a collection of classes for managing the loading and saving of data.
Datasets are ingested from various online sources in different formats (e.g. csv, txt, dat, or html). 
Each dataset class contains custom methods specific to the format of the dataset. 
For convenience, all classes also contain methods with similar namespaces to standardize the loading and saving of the data in different formats:


| Methods         | Description                                                                  |
|:----------------|:-----------------------------------------------------------------------------|
| import_from_url | Load data table from an online source to Pandas dataframe.                   |
| save_to_csv     | Save dataframe into a csv file on local drive.                               |
| import_from_csv | Load data table from a saved csv file to a Pandas dataframe.<br>(If file does not exist, it will be downloaded using the save_to_csv method.)                 |
| save_to_sql     | Save dataframe as a table in an SQL database.                                |
| load_from_sql   | Load data table from SQL database to a Pandas dataframe.                     |

Note: Some datsets contain multiple data tables that are packaged together in the same class. In these cases, the naming convention is adapted to the format: "import_< table_name >_from_< method >"

The following datasets have been implemented (note that some datsets include multiple tables).


|ClassName |Table Name                        |
|:---------|:---------------------------------|
|SBDB	   | JPL_SBDB                         |
|AstDys	   | AstDys_Elements                  |
|AstDys	   | AstDys_Families                  |
|AstDys	   | AstDys_Family_Members            |
|AstDys	   | AstDys_Synthetic_Proper_Elements |
|DAMIT	   | DAMIT_AstModel                   |
|DAMIT     | DAMIT_Model_Reference            |
|DAMIT     | DAMIT_Reference                  |
|Lowell    | Lowell_Elements                  |
|Lowell	   | Lowell_MOID                      |
|MPCORB	   | MPCORB_table                     |
|PanSTARRS | PanSTARRS                        |
|PDS_SBN   | Taxonomy_table                   |
|MITHNEOS  | MITHNEOS                         |
|SDSSMOC   | SDSS_MOC                         |
|LCDB	   | LCDB_Summary                     |
|LCDB      | LCDB_Details                     |

## Using the Datasets ClassÂ¶
The Datasets class is a rapper class allowing access to all of the datasets that have been fully implemented.

### load_dataset
The Datsets.load_dataset method can be used to load individual datasets by their table name (listed above).
The additional 'version' argument specifies if you want to re-download the most up to date dataset (version='today'), or to load in the most recent file saved on your machine (version='current').

In [2]:
# Import the Datasets class
from sr_tools.datasets import Datasets
import pandas as pd
pd.options.mode.chained_assignment = None # Surpress pandas warnings

# Load the most recent version of a dataset into a Pandas dataframe.
# (If running for the first time, no files will exist and the most recent version will be downloaded from online source.)
df = Datasets.load_dataset('MPCORB_table',version='current')
# Show the result
df

<class 'sr_tools.datasets.MPCORB'><function MPCORB.import_from_csv at 0x000001FB3E320D90>

        packed_number      H     G packed_epoch          M          w         om         i         e         n  ...  first_obs_year last_obs_year       arc      epoch     epoch_cal orbit_type  neo km_neo critical_list pha
0                   1   3.53  0.15        K20CH  205.54542   73.72487   80.27236  10.58790  0.078168  0.214242  ...          1801.0        2021.0  80355.00  2459200.5  2020-12-17.0        AST    0      0             0   0
1                   2   4.21  0.15        K20CH  187.58635  310.28810  172.96589  34.85446  0.229750  0.213282  ...          1804.0        2020.0  78894.00  2459200.5  2020-12-17.0        AST    0      0             0   0
2                   3   5.27  0.15        K20CH  170.71125  248.03277  169.85304  12.99149  0.256988  0.226162  ...          1804.0        2021.0  79259.25  2459200.5  2020-12-17.0        AST    0      0             0   0
3                   4   3.31  0.15        K20CH  258.56787  150.92240  103.80837   7.14165  0.088425  0.271504  ...          1821.0        2021.0  73050.00  2459200.5  2020-12-17.0        AST    0      0             0   0
4                   5   6.98  0.15        K20CH   65.61238  358.62503  141.57168   5.36754  0.190788  0.238719  ...          1845.0        2021.0  64284.00  2459200.5  2020-12-17.0        AST    0      0             0   0
...               ...    ...   ...          ...        ...        ...        ...       ...       ...       ...  ...             ...           ...       ...        ...           ...        ...  ...    ...           ...  ..
1081045       K21F02T  20.10  0.15        K2137  185.76967  176.81292  163.82571  24.00029  0.095771  0.403569  ...             NaN           NaN      4.00  2459280.5  2021-03-07.0        HUN    0      0             0   0
1081046       K21F02V  22.90  0.15        K2137  358.66219  173.20842  354.17357  63.11865  0.548262  0.199703  ...             NaN           NaN      3.00  2459280.5  2021-03-07.0        MCA    0      0             0   0
1081047       K21F03B  20.30  0.15        K2137  356.00787  347.30825  168.74816  52.54222  0.315277  0.304953  ...             NaN           NaN      5.00  2459280.5  2021-03-07.0        MCA    0      0             0   0
1081048       K21H03L  18.90  0.15        K214G  341.42182   97.84464  121.03255  27.28853  0.280549  0.310066  ...             NaN           NaN      3.00  2459320.5  2021-04-16.0        MCA    0      0             0   0
1081049       PLS4847  20.30  0.15        J609N   17.73304  316.52824   20.84244   1.92695  0.170398  0.500349  ...             NaN           NaN      4.00  2437200.5  1960-09-23.0        MCA    0      0             0   0

[1081050 rows x 40 columns]

## Using Individual Dataset Classes

Data can be accessed directly by using the coresponding classes of the dataset.
For example, Orbital Elements data from the Minor Planet Center can be accessed using the *MPCORB* class.

In [3]:
# Import the relevant class
from sr_tools.datasets import MPCORB

# Load the dataset into a Pandas dataframe
df = MPCORB().import_from_csv()
# Show the results
df

C:\Users\scott\Anaconda3\envs\py36\lib\site-packages\IPython\core\interactiveshell.py:3254: DtypeWarning: Columns (0,11,17,18,29) have mixed types.Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):

        packed_number      H     G packed_epoch          M          w         om         i         e         n  ...  first_obs_year last_obs_year       arc      epoch     epoch_cal orbit_type  neo km_neo critical_list pha
0                   1   3.53  0.15        K20CH  205.54542   73.72487   80.27236  10.58790  0.078168  0.214242  ...          1801.0        2021.0  80355.00  2459200.5  2020-12-17.0        AST    0      0             0   0
1                   2   4.21  0.15        K20CH  187.58635  310.28810  172.96589  34.85446  0.229750  0.213282  ...          1804.0        2020.0  78894.00  2459200.5  2020-12-17.0        AST    0      0             0   0
2                   3   5.27  0.15        K20CH  170.71125  248.03277  169.85304  12.99149  0.256988  0.226162  ...          1804.0        2021.0  79259.25  2459200.5  2020-12-17.0        AST    0      0             0   0
3                   4   3.31  0.15        K20CH  258.56787  150.92240  103.80837   7.14165  0.088425  0.271504  ...          1821.0        2021.0  73050.00  2459200.5  2020-12-17.0        AST    0      0             0   0
4                   5   6.98  0.15        K20CH   65.61238  358.62503  141.57168   5.36754  0.190788  0.238719  ...          1845.0        2021.0  64284.00  2459200.5  2020-12-17.0        AST    0      0             0   0
...               ...    ...   ...          ...        ...        ...        ...       ...       ...       ...  ...             ...           ...       ...        ...           ...        ...  ...    ...           ...  ..
1081045       K21F02T  20.10  0.15        K2137  185.76967  176.81292  163.82571  24.00029  0.095771  0.403569  ...             NaN           NaN      4.00  2459280.5  2021-03-07.0        HUN    0      0             0   0
1081046       K21F02V  22.90  0.15        K2137  358.66219  173.20842  354.17357  63.11865  0.548262  0.199703  ...             NaN           NaN      3.00  2459280.5  2021-03-07.0        MCA    0      0             0   0
1081047       K21F03B  20.30  0.15        K2137  356.00787  347.30825  168.74816  52.54222  0.315277  0.304953  ...             NaN           NaN      5.00  2459280.5  2021-03-07.0        MCA    0      0             0   0
1081048       K21H03L  18.90  0.15        K214G  341.42182   97.84464  121.03255  27.28853  0.280549  0.310066  ...             NaN           NaN      3.00  2459320.5  2021-04-16.0        MCA    0      0             0   0
1081049       PLS4847  20.30  0.15        J609N   17.73304  316.52824   20.84244   1.92695  0.170398  0.500349  ...             NaN           NaN      4.00  2437200.5  1960-09-23.0        MCA    0      0             0   0

[1081050 rows x 40 columns]